---

- hosts: deb
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes


  - name: install flameshot package
    apt: 
      name: flameshot
      state: latest


  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
