---

- hosts: all
  become: true
  tasks:

  - name: install flameshot and php packages
    apt: 
      name: 
        - flameshot
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
